### ISSUE TITLE
setting up my own server

### ISSUE THREAD

**Issue by dhacker29** [julianxhokaxhiu/LineageOTA#1]
I am trying to set this up but I keep getting
03-03 00:00:07.884: E/UpdateCheckService(1887): Error in JSON result
03-03 00:00:07.884: E/UpdateCheckService(1887): org.json.JSONException: Value <!DOCTYPE of type java.lang.String cannot be converted to JSONObject
03-03 00:00:07.884: E/UpdateCheckService(1887):     at org.json.JSON.typeMismatch(JSON.java:111)
03-03 00:00:07.884: E/UpdateCheckService(1887):     at org.json.JSONObject.<init>(JSONObject.java:159)
03-03 00:00:07.884: E/UpdateCheckService(1887):     at org.json.JSONObject.<init>(JSONObject.java:172)
03-03 00:00:07.884: E/UpdateCheckService(1887):     at com.gummy.updater.service.UpdateCheckService.parseJSON(UpdateCheckService.java:315)
03-03 00:00:07.884: E/UpdateCheckService(1887):     at com.gummy.updater.service.UpdateCheckService.getAvailableUpdatesAndFillIntent(UpdateCheckService.java:265)
03-03 00:00:07.884: E/UpdateCheckService(1887):     at com.gummy.updater.service.UpdateCheckService.onHandleIntent(UpdateCheckService.java:116)
03-03 00:00:07.884: E/UpdateCheckService(1887):     at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
03-03 00:00:07.884: E/UpdateCheckService(1887):     at android.os.Handler.dispatchMessage(Handler.java:102)
03-03 00:00:07.884: E/UpdateCheckService(1887):     at android.os.Looper.loop(Looper.java:136)
03-03 00:00:07.884: E/UpdateCheckService(1887):     at android.os.HandlerThread.run(HandlerThread.java:61)

Any clue what I might be missing?
I have the server set up at http://ironman.rombitch.com/GummyOTAserver/

**Comment by julianxhokaxhiu** [comment]
Probably your server is not running correctly this web app? Since it's trying to parse "<!DOCTYPE" I think something went in error and the JSON Java parser is just "exploding" :)

**Comment by dhacker29** [comment]
So is there anything special needed in the virtual server config for the site hosting it?

**Comment by dhacker29** [comment]
Ok so now I am at the point I get the Sorry, 404! but that's it

**Comment by julianxhokaxhiu** [comment]
Cool :) What was the mistake?

**Comment by califpornia** [comment]
Hi guys. I think error is in field naming. App returns results field, while CMUpdater application looks for result(look at s letter, it shouldn't be here). It's in index.php

**Comment by julianxhokaxhiu** [comment]
Thank you for the report. I've made a commit to fix this.
