### ISSUE TITLE
LineageOS 20 support: not working with self-signed certificates

### ISSUE THREAD

**Issue by dwardor** [julianxhokaxhiu/LineageOTA#102]
I'm trying to get this to work on lineage-20.

REST server is functional and lists (boot.im rom.zipo rom.zip.sha256sum rom.prop):
![image](https://github.com/julianxhokaxhiu/LineageOTA/assets/50771662/894a4c5d-f40a-4acf-b686-983ea5f4d119)

UnitTest fails with "undefined" That I don't know how to interpret
```
>> npm run test
>LineageOTAUnitTest@0.0.1 test
>node tests/lineage.js

undefined
```

Here is my tests/lineage.js
```
>> cat tests/lineage.js
var unirest = require('unirest'),
OtaHost = 'https://192.168.2.2/LineageOTA'; // Place here you OTA Server Url

// Provide a list of current LineageOS available updates
var getLineageList = function(){
unirest
.get(OtaHost + '/api/v1/fajita/UNOFFICIAL/77433d9635') // optional: add /<incremental_hash> to get delta updates instead
.headers({
'Cache-control' : 'no-cache',
'Content-type' : 'application/json',
'User-Agent' : 'com.cyanogenmod.updater/3.0'
})
.end(function(response){
console.log( response.body );
});
}

getLineageList();
```

But chrome gets an answer that seems to make sense : 
![image](https://github.com/julianxhokaxhiu/LineageOTA/assets/50771662/e3e1ddf8-0e27-40c7-828b-1e46982c50b0)

And finaly Lineage UpdatesActivity is not happy as it not getting the list it wants (phone is connected on home lan)
```
> logcat * | grep -i updatesactivity
06-17 16:55:28.255 10365 10365 D UpdatesActivity: Checking https://192.168.2.2/LineageOTA/api/v1/fajita/unofficial/eng.dwardo.20230611.131437
06-17 16:55:28.496 10365 22491 E UpdatesActivity: Could not download updates list
```

**Comment by julianxhokaxhiu** [comment]
It has not been tested but thanks for the report. I'll try to verify and let you know. If you happen to find the culprit, feel free to open a PR in the meantime :)

**Comment by dwardor** [comment]
Been trying to figure the "undefined" UnitTest is giving me... [Thinking Lineage Updater won't work until UnitTest works...]

Seems I have a https issue between UnitTest and REST server/underlying apache 2 as if I use http (instead of https) in UnitTest's OtaHost it gives the expected answer... 
**Don't understand why though as chrome give the correct answer with https...**

```
>> grep http tests/lineage.js
    OtaHost = 'https://192.168.2.2/LineageOTA'; // Place here you OTA Server Url

>> npm run test

> LineageOTAUnitTest@0.0.1 test
> node tests/lineage.js

undefined

>>sed "s/https/http/g" -i tests/lineage.js

>> grep http tests/lineage.js
    OtaHost = 'http://192.168.2.2/LineageOTA'; // Place here you OTA Server Url

>> npm run test

> LineageOTAUnitTest@0.0.1 test
> node tests/lineage.js

{
  id: null,
  response: [
    {
      incremental: '',
      api_level: '',
      url: 'http://192.168.2.2/LineageOTA/builds/full/lineage-20.0-20230611-UNOFFICIAL-fajita.zip',
      timestamp: 1686516180,
      md5sum: '71795dcf42637636b57a19814d29dc17',
      changes: '',
      channel: 'unofficial',
      filename: 'lineage-20.0-20230611-UNOFFICIAL-fajita.zip',
      romtype: 'unofficial',
      datetime: 1686516180,
      version: '20.0',
      id: '649f11ab05f25763e48c975f7c43525c1b98252f63dce9bc0264b18596eed913',
      size: 1045755693
    },
    {
      incremental: '',
      api_level: '',
      url: 'http://192.168.2.2/LineageOTA/builds/full/lineage-20.0-20230617-UNOFFICIAL-fajita.zip',
      timestamp: 1687010026,
      md5sum: '37918566b5a108bd1281d261bd9924e3',
      changes: '',
      channel: 'unofficial',
      filename: 'lineage-20.0-20230617-UNOFFICIAL-fajita.zip',
      romtype: 'unofficial',
      datetime: 1687010026,
      version: '20.0',
      id: '9eed5548d9213015ca28a1edacdb2332d4b378c69cce1eeda0cd0178fccc3628',
      size: 1045709672
    },
    {
      incremental: '',
      api_level: '',
      url: 'http://192.168.2.2/LineageOTA/builds/full/lineage-20.0-20230621-UNOFFICIAL-fajita.zip',
      timestamp: 1687378471,
      md5sum: 'e79d6a68e0a73d222be488a2b9a2d5d9',
      changes: '',
      channel: 'unofficial',
      filename: 'lineage-20.0-20230621-UNOFFICIAL-fajita.zip',
      romtype: 'unofficial',
      datetime: 1687378471,
      version: '20.0',
      id: '3ff178e7124a79e9b33a63c576a06dea95aa0a2c0af7a89103193eb563262adb',
      size: 1048987473
    },
    {
      incremental: '',
      api_level: '',
      url: 'http://192.168.2.2/LineageOTA/builds/full/lineage-20.0-20230709-UNOFFICIAL-fajita.zip',
      timestamp: 1688886631,
      md5sum: '27cf302f8592eef8564af2bb81548a00',
      changes: '',
      channel: 'unofficial',
      filename: 'lineage-20.0-20230709-UNOFFICIAL-fajita.zip',
      romtype: 'unofficial',
      datetime: 1688886631,
      version: '20.0',
      id: '320a58de4a771f7d239cc575f62eb84365a4245b2f6142cb984bee8242e0f420',
      size: 1048884758
    }
  ],
  error: null
}
```

**Comment by julianxhokaxhiu** [comment]
HTTPS can be tied only to a domain, not an IP. What you're trying to do is self-signed https which is think by default is not supported by Node.js nor by the UnitTest. Make sure you're using a proper HTTPS endpoint before testing again :)

**Comment by dwardor** [comment]
Same issue/behavior when replacing the ip with the fully qualified domain name...

... but your **self signed** remark was spot on !

All is well for UnitTest and in Lineage 20 now that I used cerbot (from Let’s Encrypt) to obtain certificates for my apache server :-)

![WhatsApp Image 2023-07-09 at 13 41 35](https://github.com/julianxhokaxhiu/LineageOTA/assets/50771662/74e74ded-a355-4076-a69a-fba231421202)

So I can : 

- confirm this worls with Lineage 20
- suggest to add to instructions that we don't want self signed https certificates

**Comment by julianxhokaxhiu** [comment]
Glad to hear you made it working :) About HTTPS self-signed actually is generic HTTPS knowledge and not really related to this product in particular. But thanks for the heads up nevertheless. Enjoy!
