### ISSUE TITLE
url still on 127.0.0.1

### ISSUE THREAD

**Issue by Lumince** [julianxhokaxhiu/LineageOTA#104]
I have a docker that is running on a port 3457 and we are redirecting it to another domain with port 443 so we can get https working. No matter what I do, the url ends up being 127.0.0.1 anyways?

The domain I have it set to right now is https://androidota.adamski2003.lol/builds/full/

![image](https://github.com/julianxhokaxhiu/LineageOTA/assets/10453497/16db5d54-43e2-4787-8bc1-77c3623a40d7)

**Comment by julianxhokaxhiu** [comment]
I'm not sure how are you calling the service from the docker container, but you need to use a reverse proxy on top. Can you please share how are you running the container, and serving the traffic?

**Comment by Lumince** [comment]
Hey sorry! I apparently didn't have the ports open correctly and it was just not being redirected correctly!

**Comment by julianxhokaxhiu** [comment]
Glad to hear you managed to fix it :) Enjoy!
