### ISSUE TITLE
Generic error unless change to use HTTPS

### ISSUE THREAD

**Issue by transplier** [julianxhokaxhiu/LineageOTA#13]
Using `index.js` as-is causes this error:
```
$ node index.js 
{ id: null, result: null, error: 'Error decoding JSON' }
```
If I change `OtaHost` to use the HTTPS endpoint (vs. HTTP) it works:
```
    OtaHost = 'https://download.cyanogenmod.org'; // Place here you OTA Server Url
```

**Comment by julianxhokaxhiu** [comment]
Thank you very much for the issue but it is in the wrong repository. Although the URL is there, it's mainly meant to be replaced :)

I'll anyway fix it, just for the good of all. Best regards.
