### ISSUE TITLE
Legacy support for CM

### ISSUE THREAD

**Issue by syphyr** [julianxhokaxhiu/LineageOTA#15]
I see the following error when checking for updates with cm-11.

[Wed Jan 18 20:46:05.823317 2017] [core:notice] [pid 1630] AH00094: Command line: '/usr/sbin/apache2'
[Wed Jan 18 23:20:52.677424 2017] [:error] [pid 2804] [client 192.168.1.4:54081] PHP Parse error:  syntax error, unexpected '}' in /var/www/html/CyanogenModOTA/src/CmOta.php on line 138

**Comment by julianxhokaxhiu** [comment]
Can you please try it now? I retagged the version 2.0.8 with this commit now.

**Comment by syphyr** [comment]
The error is gone now, but CMUpdater still just hangs when trying to refresh the updates. I do not see anything in the logs though.

**Comment by julianxhokaxhiu** [comment]
Had to republish with 2.0.8 tag. Can you please test now? I checked with the Unit Test and it works great in all the methods.

**Comment by syphyr** [comment]
Thank you, It is fixed now.  I was missing https://github.com/julianxhokaxhiu/LineageOTA/commit/a61a78f4b17bdaf03b8de2b26a4838244ef8e699

**Comment by julianxhokaxhiu** [comment]
Happy to hear that :)
