### ISSUE TITLE
url doesn't have the path prepended

### ISSUE THREAD

**Issue by brianjmurrell** [julianxhokaxhiu/LineageOTA#17]
When I fetch from http://example.com/lineageos/ota/api/v1/device/nightly/05793c8c55 notice that the stanza that comes back in the response doesn't have the leading "lineageos/ota/" prepended to it:

`
      {
         "incremental" : "94a030a813",
         "changes" : "http://example.com/builds/full/lineage-14
         "timestamp" : 1486238453,
         "channel" : "nightly",
         "api_level" : "25",
         "filename" : "lineage-14.1-20170204-UNOFFICIAL-<device>.zip",
         "md5sum" : "56d72db24b15ebe799d2b0b61f66db02",
         "romtype" : "nightly",
         "datetime" : 1486238453,
         "url" : "http://example.com/builds/full/lineage-14.1-2
      }

`

**Comment by julianxhokaxhiu** [comment]
Hi @brianjmurrell, [your basePath](https://github.com/julianxhokaxhiu/LineageOTA/blob/2.0/index.php#L31) is not set correctly. Please fix it.

**Comment by brianjmurrell** [comment]
Or how about the solution in PR #18?  I'm not a PHP expert (by a long shot) so I don't know if there are cases where that solution won't work but it seems to work here.
