### ISSUE TITLE
changelog for legacy updater unavailable

### ISSUE THREAD

**Issue by syphyr** [julianxhokaxhiu/LineageOTA#23]
I am unable to download/view the changelog with the legacy CM Updater (cm-11.0).  CM Updater just times out when attempting to download the changelog.  When I look at the unit test for cm-11.0, this is what I see below.  I noticed that there is no link for the changelog in the response for the unit test.  This was working a while back, so I'm not exactly sure what changed.

{ id: null,
  response: 
   [ { incremental: '49e89cf66b',
       api_level: '19',
       url: 'http://192.168.1.5/CyanogenModOTA/builds/full/cm-11-20170508-NIGHTLY-p3110.zip',
       timestamp: 1494254395,
       md5sum: '1c970862c206ceb43d7de6ccf3c2363a',
       changes: '',
       channel: 'nightly',
       filename: 'cm-11-20170508-NIGHTLY-p3110.zip',
       romtype: 'nightly',
       datetime: 1494254395 } ],
  error: null }

**Comment by julianxhokaxhiu** [comment]
Unfortunately my Internet connection at home is down. As soon as it will work again, I will take a look at it. Thanks for the report.

**Comment by syphyr** [comment]
The commit that broke the changelogs is this:
(2 months ago) Remove memcached support (Julian Xhokaxhiu)

**Comment by syphyr** [comment]
I wanted to mention that I reverted the OTA Server code back to a previously known working version and I still had the problem with the changelog not downloading.  So, now I am starting to think it was not a recent change in the OTA server that is causing the problem. Although, my ROM has also not changed, so now I dont understand why it does not work anymore.  Perhaps there is Ubuntu security update for nginx that broke this?  I'm using Ubuntu 16.04.

**Comment by syphyr** [comment]
I changed the unit test so that It would test the legacy api with the following commit and I still can not get a path to show up for the changelog when I perform a unit test.

https://github.com/syphyr/CyanogenModOTAUnitTest/commit/efd6fda6d3bb5e10f434392bc7931a415dfdddf2

Would you happen to have any ideas on how I might be able to debug this?  I do not see anything in the logs that indicates a problem.  Updating the zip file works as expected.  The only problem is with the Changelog.

**Comment by julianxhokaxhiu** [comment]
Sorry for the long delay. Unfortunately I have no internet at home, I just have a tethering option which is not very fast at the moment. As soon as I will have stable internet back, I will test it ( as I need to download at least one ROM zip with CM11 ).

Thank you for the patience.

---

I just published the 2.2.0, containing one commit from @corna that fixes the Changelog URL generation. Can you please try it?

**Comment by syphyr** [comment]
After updating, the changelog path is now showing up in the unit_test.

{ id: null,
  result: 
   [ { incremental: '29798d1dab',
       api_level: '19',
       url: 'http://192.168.1.5/CyanogenModOTA/builds/full/cm-11-20170523-NIGHTLY-p3110.zip',
       timestamp: 1495555849,
       md5sum: '903866c29b77592dc3c12f1f99c31d74',
       changes: 'http://192.168.1.5/CyanogenModOTA/builds/full/cm-11-20170523-NIGHTLY-p3110.html',
       channel: 'nightly',
       filename: 'cm-11-20170523-NIGHTLY-p3110.zip',
       romtype: 'nightly',
       datetime: 1495555849 } ],
  error: null }

I will create a new build tomorrow and verify if it is working with my device running cm-11.  

Thanks.

**Comment by syphyr** [comment]
It's fixed now.  Thank you.

**Comment by julianxhokaxhiu** [comment]
Nice to know! Thanks for the feedback :)
