### ISSUE TITLE
Scan for zips in the subdirectories of builds/full/

### ISSUE THREAD

**Issue by corna** [julianxhokaxhiu/LineageOTA#24]
Is it possible to implement the search for build zips also in the subdirs of builds/full/? At the moment all the zips must be inside that folder and, when many builds of many devices are present, the folder becomes messy.

With this feature enabled one can organize the builds in the respective device folder:
 * builds/full/bacon/
 * builds/full/onyx/
 * builds/full/thea/
 * ...

**Comment by julianxhokaxhiu** [comment]
Sure, I will take a look at it soon as I have my Internet connection back. Should be quite easy to be implemented.

**Comment by corna** [comment]
I've done it in corna/LineageOTA@e655d3067bbf94e2ef2000f1e85bf1eaa15e3f63
As soon as I test it I'll open a PR

**Comment by corna** [comment]
With my current patch the url member of Build is not correct (as it is [fixed at 'buildsPath'](https://github.com/julianxhokaxhiu/LineageOTA/blob/2.0/src/Helpers/Build.php#L74)) and unfortunately I don't know PHP; can you implement it?

**Comment by corna** [comment]
Done it #26

**Comment by julianxhokaxhiu** [comment]
Merged it. Thank you :)
