### ISSUE TITLE
Builds have specific naming?

### ISSUE THREAD

**Issue by Moocow9m** [julianxhokaxhiu/LineageOTA#28]
Is there a format that the builds HAVE to be? I places a custom signed build to the full folder and ran the unit test and got errors. Is there a format I am missing? I named it like a LineageOS official build and it worked. What is the format?

**Comment by julianxhokaxhiu** [comment]
Yes, it is expected to be the one that you get once you finish to build. Do not rename the file.

**Comment by Moocow9m** [comment]
@julianxhokaxhiu I have the build signed and specify the output name as lineage does in it's example on the wiki
