### ISSUE TITLE
Latest CMUpdater changed API

### ISSUE THREAD

**Issue by syphyr** [julianxhokaxhiu/LineageOTA#29]
On June 17th, there were several commits to LineageOS/android_packages_apps_CMUpdater which changed the way builds are detected.  CMUpdater no longer sees new builds from the LineageOTA Server.

https://review.lineageos.org/#/q/project:LineageOS/android_packages_apps_CMUpdater

Out of these new changes, this one looks like it might be the problem:

https://review.lineageos.org/#/c/177731/

**Comment by im-not-here-anymore** [comment]
Adding  a version field to Builds.php response array allows updates to work again.  I hard coded a '14.1' response  and updates are working again. It's an ugly kludge though

**Comment by julianxhokaxhiu** [comment]
Thanks, I'll take care of this later today if possible.

**Comment by julianxhokaxhiu** [comment]
Please update to 2.3.0
