### ISSUE TITLE
delta build won't be automatically built

### ISSUE THREAD

**Issue by moetayuko** [julianxhokaxhiu/LineageOTA#3]
i run the program on my vps. xdelta3 is installed through apt-get. full packages are uploaded to builds/full, such as builds/full/cm-11-20141004-NIGHTLY-xxxx.zip. filemode 777.but it doesn't work.

no delta builds are automatically built:(

what's wrong with my steps?

thanks for replying:P @julianxhokaxhiu

**Comment by moetayuko** [comment]
also, package push amount should be limited to 3.cmupdater doesn't work when there're more than 3 builds under full directory.

**Comment by julianxhokaxhiu** [comment]
Delta builds should be rebuilt entirely. I'm not sure that delta builds are working well so I'm don't give any guarantee of that.

About the amount of builds, as much as I know, CMOta is getting the latest built that is newest based on your current build. So I think that the limitation is not needed (based on the current source of CM Ota of course).

Anyway, this project is going to be rewritten again entirelly in Python so this PHP version is somewhat deprectaed by me, at least :)

**Comment by moetayuko** [comment]
hmm.if CMOTA receive more than 3 builds, it will just keep searching but not return anything. that's what i met.

looking forward to seeing your next version:)awesome work
