### ISSUE TITLE
Notified on a new rom even though the latest rom is installed.

### ISSUE THREAD

**Issue by patauanorth** [julianxhokaxhiu/LineageOTA#30]
Currently the OTA server returns the file modification time on the webserver of any roms in the builds folder. This means the last build listed on the server will always appear to be newer than the latest installed build as $this->timestamp = filemtime( $this->filePath ); in Build.php will always be later than the  ro.build.date.utc field in build.prop in the rom. As a result you get prompted to download the latest rom even though its already installed. 

Removing the filemtime test and replacing it with the ro.build.date.utc in build.prop fixes this admittedly cosmetic issue.

**Comment by julianxhokaxhiu** [comment]
Thanks, I'll look into this :)

**Comment by julianxhokaxhiu** [comment]
Please update to 2.3.0
