### ISSUE TITLE
unique id field required soon

### ISSUE THREAD

**Issue by syphyr** [julianxhokaxhiu/LineageOTA#32]
LineageOS is soon going to be using a new version of their "Updater" application found here:

https://github.com/gmrt/android_packages_apps_Updater

The json parser is now looking for an additional "id" field.  Currently, the response for "id" is "null" with this OTA Server.

The new Updater is looking for these fields:

https://github.com/gmrt/android_packages_apps_Updater/blob/master/src/org/lineageos/updater/misc/Utils.java#L63-L68

So, the solution to fixing the OTA Server to work with the new LineageOS Updater is to generate a unique number for the "id" field.

**Comment by julianxhokaxhiu** [comment]
Wow, thanks! I'll try to apply a patch. Sounds quite easy to be accomplished.

**Comment by julianxhokaxhiu** [comment]
@syphyr Can you please try to checkout the latest master status? If it works I can make a proper release :)

**Comment by syphyr** [comment]
Yes, the new "id" field is recognized and everything is working as expected.  Thank you for the great work!

**Comment by julianxhokaxhiu** [comment]
Always welcome, and thank you for the report :)

I'll do an official release later/tomorrow maximum.

_Sent from my OnePlus ONEPLUS A5000 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

---

//EDIT: 2.4.0 released!
