### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by princeofgiri** [julianxhokaxhiu/LineageOTA#33]
Is there any sort brief how to use?

**Comment by julianxhokaxhiu** [comment]
https://github.com/julianxhokaxhiu/LineageOTA#how-to-use

**Comment by princeofgiri** [comment]
I already read it, but still failed. when accessing server, got 404. are you use apache?

**Comment by julianxhokaxhiu** [comment]
Yes, and also Nginx. For apache you have already the `.htaccess` included.

The setup is pretty straightforward. Nothing special to be done.

**Comment by janengelmohr** [comment]
@princeofgiri when in doubt, check your apache logs :)

**Comment by julianxhokaxhiu** [comment]
I assume that everything is fine now :) Closing, but feel free to re-open if the issue persists. Thank you!
