### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by Charles-IV** [julianxhokaxhiu/LineageOTA#34]
localhost/LineageOTA returns a 404 for me.
I copied it to var/www/html, and that doesn't bring up a 404, but I'm not sure if the actual updater server bit will still work.
Is it meant to be in var/www/html, or do I need to do something for it to work in var/www?

**Comment by julianxhokaxhiu** [comment]
Just follow the setup instructions. This feels like a configuration issue from your side.

Feel free to take a look at the docker image if you're unsure how the system must be setup.

Best regards.

**Comment by Charles-IV** [comment]
I'll try again with docker, but I ran `cd /var/www/ && composer create-project julianxhokaxhiu/lineage-ota LineageOTA` after installing composer, and ran it all as root. I also ran `service apache2 restart` several times to see if that would work.

**Comment by julianxhokaxhiu** [comment]
Check if you have the rewrite module enabled.

**Comment by Charles-IV** [comment]
what's that?

**Comment by julianxhokaxhiu** [comment]
Please make use of the dedicated XDA forum topic. Here we discuss only technical issues. Thank you.

**Comment by Charles-IV** [comment]
one thing is when i run the code beginning with `docker run`, I get the output: 
```
424a760588b9a9348ed6f4b445dad939f0f81e9da5fcb65b482f088c0defc97f
docker: Error response from daemon: driver failed programming external connectivity on endpoint distracted_goldwasser (3ac89b6a899de711393b18c754011b1dd4032f7b582dd8718a48406dc11f5d31): Bind for 0.0.0.0:80 failed: port is already allocated.
```
Could this mean something?

I also ran `a2enmod rewrite`, and restarted apache, but ~~it came out with an error~~(fixed that now) still no result.

**Comment by Charles-IV** [comment]
I have put it in /var/www/html and left it, as I am now trying to use the lineage_updater.

**Comment by BenJule** [comment]
0.0.0.0:80 is still in use!

**Comment by Charles-IV** [comment]
I saw saw someone else had this error on xda, but unfortunately I appeared to have screwed up my environment, and can't start apache, purging and re-installing didn't work.
It doesn't matter but it would have just been cool, but if I get it set up on my raspberry pi, which is what I would have done, I will be starting afresh, and it would be fine.
