### ISSUE TITLE
hey, having a few issues getting this working

### ISSUE THREAD

**Issue by ItsOnlyBinary** [julianxhokaxhiu/LineageOTA#38]
Hi, could you please hit me up on freenode when you have a moment. Having a few issues getting this working with current builds of cm-14.1

I'm NucWin on #lineageos-dev we have spoke before but i cannot for the life of me remember your irc nick.

ps all your info/social stuff on your website. but no email address to be found anywhere. hence why im here

**Comment by julianxhokaxhiu** [comment]
Hi, that's fine. Feel free to drop your question here. Maybe can be useful to othes using this project too.

**Comment by ItsOnlyBinary** [comment]
ok ive had it setup for a while. and its been working fine. recently it has stopped working.
i can still see the page requests in nginx logs and they are returning 200. Ive copied the request and visited in my browser and json is being returned with my zips. but phone always says there is no updates.

**Comment by ItsOnlyBinary** [comment]
11-14 18:01:23.598 30852  8965 D DownloadClient: Download failed
11-14 18:01:23.598 30852  8965 D DownloadClient: java.net.ProtocolException: Expected ':status' header not present
11-14 18:01:23.598 30852  8965 D DownloadClient: 	at com.android.okhttp.internal.http.FramedTransport.readNameValueBlock(FramedTransport.java:197)
11-14 18:01:23.598 30852  8965 D DownloadClient: 	at com.android.okhttp.internal.http.FramedTransport.readResponseHeaders(FramedTransport.java:104)
11-14 18:01:23.598 30852  8965 D DownloadClient: 	at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:907)
11-14 18:01:23.598 30852  8965 D DownloadClient: 	at com.android.okhttp.internal.http.HttpEngine.-wrap0(HttpEngine.java)
11-14 18:01:23.598 30852  8965 D DownloadClient: 	at com.android.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:892)
11-14 18:01:23.598 30852  8965 D DownloadClient: 	at org.lineageos.updater.download.OkHttpDownloadClient$2.intercept(OkHttpDownloadClient.java:157)
11-14 18:01:23.598 30852  8965 D DownloadClient: 	at com.android.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:869)
11-14 18:01:23.598 30852  8965 D DownloadClient: 	at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:750)
11-14 18:01:23.598 30852  8965 D DownloadClient: 	at com.android.okhttp.Call.getResponse(Call.java:268)
11-14 18:01:23.598 30852  8965 D DownloadClient: 	at com.android.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:224)
11-14 18:01:23.598 30852  8965 D DownloadClient: 	at com.android.okhttp.Call.getResponseWithInterceptorChain(Call.java:195)
11-14 18:01:23.598 30852  8965 D DownloadClient: 	at com.android.okhttp.Call.-wrap0(Call.java)
11-14 18:01:23.598 30852  8965 D DownloadClient: 	at com.android.okhttp.Call$AsyncCall.execute(Call.java:162)
11-14 18:01:23.598 30852  8965 D DownloadClient: 	at com.android.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
11-14 18:01:23.598 30852  8965 D DownloadClient: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
11-14 18:01:23.598 30852  8965 D DownloadClient: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
11-14 18:01:23.598 30852  8965 D DownloadClient: 	at java.lang.Thread.run(Thread.java:761)
11-14 18:01:23.598 30852  8965 E UpdatesActivity: Could not download updates list

**Comment by ItsOnlyBinary** [comment]
Seems having http2 enabled for one of my other sites was applying to all sites.
after removing http2 and restarting my sever it is now downloading the list and seems to be working although its still showing an error in logcat

11-14 18:28:33.152 30852 10858 D DownloadClient: Downloading
11-14 18:28:33.157 30852 10858 D DownloadClient: Download complete
11-14 18:28:33.158 30852 30852 D UpdatesActivity: List downloaded
11-14 18:28:33.158 30852 30852 D UpdatesActivity: Adding remote updates
11-14 18:28:33.176 30852 30852 D UpdaterController: Adding download: b717250563977e398719df5fd4cbfabf9d5da1429616b2f16ba6fe94a1ffa39e
11-14 18:28:33.176 30852 30852 D UpdaterController: Download (b717250563977e398719df5fd4cbfabf9d5da1429616b2f16ba6fe94a1ffa39e) already added
11-14 18:28:33.176 30852 30852 D UpdaterController: Adding download: b89bc95435aa20d55bcaa9eb1992d56e7828029aa073df6ec735c9897340db08
11-14 18:28:33.176 30852 30852 D UpdaterController: Download (b89bc95435aa20d55bcaa9eb1992d56e7828029aa073df6ec735c9897340db08) already added
11-14 18:28:33.201 30852 30852 E UpdatesActivity: Could not read json
11-14 18:28:33.201 30852 30852 E UpdatesActivity: org.json.JSONException: End of input at character 0 of 
11-14 18:28:33.201 30852 30852 E UpdatesActivity: 	at org.json.JSONTokener.syntaxError(JSONTokener.java:449)
11-14 18:28:33.201 30852 30852 E UpdatesActivity: 	at org.json.JSONTokener.nextValue(JSONTokener.java:97)
11-14 18:28:33.201 30852 30852 E UpdatesActivity: 	at org.json.JSONObject.<init>(JSONObject.java:156)
11-14 18:28:33.201 30852 30852 E UpdatesActivity: 	at org.json.JSONObject.<init>(JSONObject.java:173)
11-14 18:28:33.201 30852 30852 E UpdatesActivity: 	at org.lineageos.updater.misc.Utils.parseJson(Utils.java:125)
11-14 18:28:33.201 30852 30852 E UpdatesActivity: 	at org.lineageos.updater.misc.Utils.checkForNewUpdates(Utils.java:191)
11-14 18:28:33.201 30852 30852 E UpdatesActivity: 	at org.lineageos.updater.UpdatesActivity.processNewJson(UpdatesActivity.java:331)
11-14 18:28:33.201 30852 30852 E UpdatesActivity: 	at org.lineageos.updater.UpdatesActivity.-wrap2(UpdatesActivity.java)
11-14 18:28:33.201 30852 30852 E UpdatesActivity: 	at org.lineageos.updater.UpdatesActivity$5$2.run(UpdatesActivity.java:381)
11-14 18:28:33.201 30852 30852 E UpdatesActivity: 	at android.os.Handler.handleCallback(Handler.java:751)
11-14 18:28:33.201 30852 30852 E UpdatesActivity: 	at android.os.Handler.dispatchMessage(Handler.java:95)
11-14 18:28:33.201 30852 30852 E UpdatesActivity: 	at android.os.Looper.loop(Looper.java:154)
11-14 18:28:33.201 30852 30852 E UpdatesActivity: 	at android.app.ActivityThread.main(ActivityThread.java:6186)
11-14 18:28:33.201 30852 30852 E UpdatesActivity: 	at java.lang.reflect.Method.invoke(Native Method)
11-14 18:28:33.201 30852 30852 E UpdatesActivity: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
11-14 18:28:33.201 30852 30852 E UpdatesActivity: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

**Comment by julianxhokaxhiu** [comment]
I'm sorry but I can't help you much with that. As long as it downloads, it seems that the JSON is fine. Feel free to ask on the related XDA Thread.

Best regards.
