### ISSUE TITLE
The requested URL /api was not found on this server.

### ISSUE THREAD

**Issue by fuzzy7k** [julianxhokaxhiu/LineageOTA#4]
Am I missing something?

I'm using Apache on CentOS with the php5_module. The server is up. If I browse to it, I am redirected the the builds directory but when I run the CyanogenModOTAUnitTest I get:

"The requested URL /api was not found on this server."

**Comment by julianxhokaxhiu** [comment]
You're missing the Url Rewrite module. And make sure that htaccess can be readed from your setup.

**Comment by julianxhokaxhiu** [comment]
As you see in the source code, [you have to change the host line](https://github.com/julianxhokaxhiu/CyanogenModOTAUnitTest/blob/master/index.js#L25) to your one :)

**Comment by fuzzy7k** [comment]
I did that, I have also changed the device to that of the build that I placed in builds/full. When I run the unit test, or run the update check from my phone, I get the following in /var/log/httpd/access_log:

192.168.1.5 - - [28/Sep/2015:09:50:30 -0400] "POST /api HTTP/1.1" 404 201 "-" "com.cyanogenmod.updater/2.2"

With your response I gather it must be something simple. I've verified that all of the files are owned by apache:apache. I suspect that either I need to pass some option to apache since /api does not physically exist, or that the php is being handled incorrectly. I've been looking, but nothing yet.

**Comment by julianxhokaxhiu** [comment]
Is the Url Rewrite module enabled? It is possible to have a public Url to your setup?

**Comment by fuzzy7k** [comment]
You nailed it. The AllowOverride directive was required for my setup.

```
<Directory /var/www/CyanogenModOTA>
    AllowOverride All
</Directory>
```

For those unaware, as I was, this directive dictates what other directives are honoured in .htaccess files. The .htaccess file that is shipped with this project turns on the RewriteEngine. I can get by with AllowOverride FileInfo also.

http://httpd.apache.org/docs/2.4/mod/core.html#allowoverride

**Comment by julianxhokaxhiu** [comment]
Glad that it worked :)
