### ISSUE TITLE
julianxhokaxhiu your SHIT program don;t work

### ISSUE THREAD

**Issue by gurussia** [julianxhokaxhiu/LineageOTA#45]
julianxhokaxhiu it is not working. julianxhokaxhiu dont work. we install npm, we install composer and we try from unsuported device and it comment 404. cm.update point to: https://yourdomain.com/Li/api and it comment 404
we try lienage ota test and manual is misconfigured, but we put correct configuration and it comment after some 2 min. of wait or more undefined, we try with lineage " with lineage it was fast " with cm and cm:delta it wait 2 min. or 5 min. and undefined. julianxhokaxhiu your manual are misconfigured.

Now in ubuntu 17.10 it don't have npm we have to install development update to instal npm, so in your manual  you don't comment how to install npm this is serious problem for other peoples becouse in ubuntu normal repository npm can';t be installed. julianxhokaxhiu you now from the time we use SHIT linux we every day are SICK OF SHITS like your yours who try LIE, try comment FALSE programs, unexplained, misconfigured, try to broke humankind linux operation system include android smartphone and etc. In internet we every day see peoples worse than you julianxhokaxhiu that try LIE, do this to compile android, make this and they just LIE worse than you, im not gonna say how to find how they LIE, but you are example julianxhokaxhiu HOW peoples like you LIE include you are worse. with your minus 1 mb. SHIT program person can lost 2 days if he is not developer, but that is problem becouse GITHUB has to delete SHIT women that try LIE. it is shame that who pay you to LIE humankind. it is SHAME that github permit SHIT include github HAS TO FORCE all developers to PUT from 0 to 100 % how they SHIT software works, failing this developers has to be BLOCKED. julianxhokaxhiu you buy car, what will happend if when you julianxhokaxhiu buy TRABANT OR LADA and there is not 100 % HUMANKIND manuals. julianxhokaxhiu it is 100 % sure that you julianxhokaxhiu are gonna write the same things but the things is that you are not gonna write it becouse how i say julianxhokaxhiu you are WORSE than the worse, becouse i;m not the first to tell you the true.

**Comment by julianxhokaxhiu** [comment]
Usually I tend to help, but since you started by fingerpointing and offending without even giving me a chance to help you, I have to close this one. Learn to moderate yourself, and respect a piece of work that is done without any profit in mind. Feel free to write your own or use something else.
