### ISSUE TITLE
I can't remove the docker command

### ISSUE THREAD

**Issue by Charles-IV** [julianxhokaxhiu/LineageOTA#49]
So I ran the docker command once a while ago to see if I could get this to work, however ever since then I've had a problem with apache and anything using port 80. Once I learnt docker was the problem, I've run `docker ps`, and `julianxhokaxhiu/lineageota` is there, unless I've already killed it. When I reboot, it's back. I've tried `docker update --restart=no name-of-container`, then killing it and rebooting, but it's there again.

Please help me get rid of this, currently I can't run another apache thing, as most of the time I'd rather clone this into /var/www/html and using apache, but I can't because of this.

It would be helpful for future newbs like me if readme was also updated to reflect how to remove the docker container when it is no longer wanted.

Many thanks, and other than this, I really like this project, well done!

**Comment by julianxhokaxhiu** [comment]
Thank you. Although this is not a real issue for this project, in order to remove the container you can do:
```
$ docker stop <your_container_name_or_id>
$ docker rm <your_container_name_or_id>
```

**Comment by Charles-IV** [comment]
I think I did that but I'm not sure if it's going to come back again when I next reboot.
I just think it would be useful to update the documentation to help those struggling out, but I fully recognise that it is not exactly a valid issue.
