### ISSUE TITLE
HTTP 403

### ISSUE THREAD

**Issue by brenosilva** [julianxhokaxhiu/LineageOTA#50]
Hello,

I setup the project on my server.
All installation looks good. I enabled mod_write and php7.0
The build is doing the correct GET : 

[15/Jun/2018:22:12:08 +0000] "GET /DfxOTA/api/v1/herolte/dfx/dd4c8a80f4 HTTP/1.1" 403 551 "-" "Dalvik/2.1.0 (Linux; U; Android 7.1.2; SM-G930F Build/NJH47F)"

The ota build is there:
root@dfx-ota:/var/www/html/DfxOTA# ls -lisa builds/full/lineage_herolte-ota-dd4c8a80f4.zip 
7098 480060 -rw-r--r-- 1 www-data www-data 491577822 Jun 15 21:50 builds/full/lineage_herolte-ota-dd4c8a80f4.zip
root@dfx-ota:/var/www/html/DfxOTA# 

However i'm seeing HTTP Forbidden. Started to see it when added AllowOverride All. Before it server was returning 404.

<Directory />
        Options FollowSymLinks
        AllowOverride All
        Require all denied
</Directory>

<Directory /var/www/html/DfxOTA>
        Options FollowSymLinks
        AllowOverride All
        Require all denied
</Directory>

Any idea ?

Thanks in advance

**Comment by brenosilva** [comment]
I built a nightly release type. Set AllowOverride All and Require all granted on apache.conf. Now 
access.log:
"GET /DfxOTA/api/v1/herolte/nightly/158c0a311a HTTP/1.1" 500 2737 "-" "Dalvik/2.1.0 (Linux; U; Android 7.1.2; SM-G930F Build/NJH47F)"

build file:
ls /var/www/html/DfxOTA/builds/full/lineage-14.1-20180616-NIGHTLY-herolte.zip 

500 Internal Server Error
Undefined offset: 0 (8)
#0 /var/www/html/DfxOTA/src/Helpers/Build.php(256): flight\Engine->handleError(8, 'Undefined offse...', '/var/www/html/D...', 256, Array)
#1 /var/www/html/DfxOTA/src/Helpers/Build.php(70): JX\CmOta\Helpers\Build->removeTrailingDashes(Array)
#2 /var/www/html/DfxOTA/src/Helpers/Builds.php(153): JX\CmOta\Helpers\Build->__construct('lineage_herolte...', '/var/www/html/D...')
#3 /var/www/html/DfxOTA/src/Helpers/Builds.php(49): JX\CmOta\Helpers\Builds->getBuilds()
#4 /var/www/html/DfxOTA/vendor/mikecao/flight/flight/core/Loader.php(123): JX\CmOta\Helpers\Builds->__construct()
#5 /var/www/html/DfxOTA/vendor/mikecao/flight/flight/core/Loader.php(80): flight\core\Loader->newInstance('\\JX\\CmOta\\Helpe...', Array)
#6 /var/www/html/DfxOTA/vendor/mikecao/flight/flight/Engine.php(74): flight\core\Loader->load('builds', true)
#7 /var/www/html/DfxOTA/vendor/mikecao/flight/flight/core/Dispatcher.php(196): flight\Engine->__call('builds', Array)
#8 /var/www/html/DfxOTA/vendor/mikecao/flight/flight/Flight.php(77): flight\core\Dispatcher::invokeMethod(Array, Array)
#9 /var/www/html/DfxOTA/src/CmOta.php(111): Flight::__callStatic('builds', Array)
#10 /var/www/html/DfxOTA/vendor/mikecao/flight/flight/core/Dispatcher.php(171): JX\CmOta\CmOta->JX\CmOta\{closure}('herolte', 'nightly', '158c0a311a')
#11 /var/www/html/DfxOTA/vendor/mikecao/flight/flight/core/Dispatcher.php(143): flight\core\Dispatcher::callFunction(Object(Closure), Array)
#12 /var/www/html/DfxOTA/vendor/mikecao/flight/flight/Engine.php(312): flight\core\Dispatcher::execute(Object(Closure), Array)
#13 /var/www/html/DfxOTA/vendor/mikecao/flight/flight/core/Dispatcher.php(196): flight\Engine->_start()
#14 /var/www/html/DfxOTA/vendor/mikecao/flight/flight/core/Dispatcher.php(142): flight\core\Dispatcher::invokeMethod(Array, Array)
#15 /var/www/html/DfxOTA/vendor/mikecao/flight/flight/core/Dispatcher.php(48): flight\core\Dispatcher::execute(Array, Array)
#16 /var/www/html/DfxOTA/vendor/mikecao/flight/flight/Engine.php(65): flight\core\Dispatcher->run('start', Array)
#17 /var/www/html/DfxOTA/vendor/mikecao/flight/flight/core/Dispatcher.php(196): flight\Engine->__call('start', Array)
#18 /var/www/html/DfxOTA/vendor/mikecao/flight/flight/Flight.php(77): flight\core\Dispatcher::invokeMethod(Array, Array)
#19 /var/www/html/DfxOTA/src/CmOta.php(69): Flight::__callStatic('start', Array)
#20 /var/www/html/DfxOTA/index.php(37): JX\CmOta\CmOta->run()
#21 {main}

**Comment by julianxhokaxhiu** [comment]
```
GET /DfxOTA/api/v1/herolte/nightly/158c0a311a
```

It looks like your device is trying to fetch a delta file. Make sure it is available in the delta folder. Otherwise please check your own Android code to make sure it fetches the full zip file instead.

It has nothing to do with LineageOTA itself. Also please make sure you use the XDA thread for these kind of issues. Create one here only when you're 100% sure it's related to the code and not to your Android ROM.

Thank you.

**Comment by brenosilva** [comment]
I also included the delta lineage_herolte-ota-158c0a311a.zip into builds/delta but received

"GET /DfxOTA/api/v1/herolte/nightly/158c0a311a HTTP/1.1" 404 544 "-" "Dalvik/2.1.0 (Linux; U; Android 7.1.2; SM-G930F Build/NJH47F)"

So, looks like some issue in the code?

TO only request full images should i just remove {incr} from the url ?
Thanks
