### ISSUE TITLE
URL Wrong when using apache reverse proxy

### ISSUE THREAD

**Issue by newhinton** [julianxhokaxhiu/LineageOTA#56]
I am running this behind an apache reverse proxy, and i needed to edit the sourcefiles to get the proper url. I am using docker to run the ota-server, and the download url for the files are the defined target of the proxy (eg. 127.0.0.1:6677). Therefore the device can't download the updates (but can see them via the api)

If i preserve the host, the ip changes to the host but the protocoll is http instead of my apache's https. Also subdirectories are not preseved.

Did i do the proxy wrong, or is this an actual bug?

**Comment by julianxhokaxhiu** [comment]
Guess is a bug on your side and RP was one of the first I've personally tested as I used to run it on one of my personal VPS ( see https://github.com/julianxhokaxhiu/vps-powered-by-docker/blob/master/modules/lineage.lan.sh )
