### ISSUE TITLE
Creating Delta Builds

### ISSUE THREAD

**Issue by GT3CH1** [julianxhokaxhiu/LineageOTA#64]
There is no documentation on how to name delta builds.  How would you name delta builds for this api?

**Comment by julianxhokaxhiu** [comment]
> There is no documentation on how to name delta builds. How would you name delta builds for this api?

Hi,

Delta file support was never actually fully tested as I never had a chance to create OTAs. Although as far as I remember it just follows the filename syntax, which comes in a flavor `[SOURCE_HASH]-[DEST_HASH].zip` and the OTA code just builds all the metadata based on this assumption ( see https://github.com/julianxhokaxhiu/LineageOTA/blob/2.0/src/Helpers/Builds.php#L97 and https://github.com/julianxhokaxhiu/LineageOTA/blob/2.0/src/Helpers/Build.php#L127 ).

ZIP file creation is not ( and never will be ) managed by LineageOTA, but instead you have to rely on the build system of LineageOS itself.

Feel free to test it and report back if you have a valid OTA file to test :)

Cheers,
Julian

**Comment by GT3CH1** [comment]
@julianxhokaxhiu I'm currently exploring the API.  At the moment, it looks like 'source_incremental' on https://github.com/julianxhokaxhiu/LineageOTA/blob/2.0/src/CmOta.php#L118 is not being sat properly.  I'm not getting an incremental from the response, but if I add `'test' => $incrementalVersion,` to CmOta#L129 then I am able to see the value in the call to the api (api/v1/device... etc).  

I am unfamiliar with Flight, but I am learning it as I am working on this.

**Comment by julianxhokaxhiu** [comment]
> I am unfamiliar with Flight, but I am learning it as I am working on this.

Feel free to check this script I've developed to test all the scenarios https://github.com/julianxhokaxhiu/LineageOTAUnitTest
