### ISSUE TITLE
Add an option to use a different builds directory 

### ISSUE THREAD

**Issue by ADeadTrousers** [julianxhokaxhiu/LineageOTA#69]
Hi.

Currently I'm publishing my releases here on github and I want to keep this as an alternative way. Also I don't want to invest too much into a webspace for my projct and I don't like free webhosts too much either with all their advertising. So it would be awesome if your OTA-Updater could serve the needed files from a different location (eg. github) than the default `/builds/full` and `/builds/delta` directory.
Honestly I'm not sure how much really needs to be changed, cause many of the commands you used (ex. `filesize`) should work with `http(s);//` urls.
Maybe you can look into this and give me a short response.
If you don't want to (or don't have the time for it) would you like me to provide a pull request for this or should I just fork and don't bother you anymore?

wkr ADT

**Comment by julianxhokaxhiu** [comment]
Hi,

Thanks for the issue. As you're hosting your own builds somewhere else, I suggest you looking for a completely different approach that is completely server-less, see https://github.com/julianxhokaxhiu/ota.julianxhokaxhiu.com

Regarding LineageOTA I think it fulfills another spot that is completely different than yours, but if you can find a smart way that could fit both, I'd be totally happy to review a PR and merge it :)

Let me know what you think.

**Comment by ADeadTrousers** [comment]
I did a little bit of research on your serverless approach:
What I don't understand is how everything is connected and which parts need a login or user account being set up to work.
The page https://ota.julianxhokaxhiu.com/ resides on github.com (with a custom domain I guess).
There are two scripts from cloudflare included (anchor and rocket loader) which I suppose are for the redirect, but where is that configured?
And that is how far I could follow your approach. So I don't know how travis is involed in this. As far as I know travis is for actually building things from code. And last but not least Basketbuild, which I suppose is for the actual file storage, which in my case would be github.

As of this approach which uses only PHP I'm much more familiar with:
I just had to do a little bit of reasearch on Composer and Flight, but I think I get the hang of it now.
So I'm pretty sure that integrating an API call to github for fetching the releases of a repository and using these informations for serving the response would be possible. Only thing left to know is if the LineageOS Updater would accept a file from a different location (domain) than the updater script itself.

**Comment by julianxhokaxhiu** [comment]
> I did a little bit of research on your serverless approach:
> What I don't understand is how everything is connected and which parts need a login or user account being set up to work.
> The page https://ota.julianxhokaxhiu.com/ resides on github.com (with a custom domain I guess).
> There are two scripts from cloudflare included (anchor and rocket loader) which I suppose are for the redirect, but where is that configured?
> And that is how far I could follow your approach. So I don't know how travis is involed in this. As far as I know travis is for actually building things from code. And last but not least Basketbuild, which I suppose is for the actual file storage, which in my case would be github.

As written in the README of that repo, the idea is to use Cloudflare to handle required API redirects needed by the LineageOS updater app. Regarding Travis, it will build the API object response everytime you trigger the build ( you can trigger it manually or for eg. every night ). The API response will then be published on the github repo on the `gh-pages` repo allowing to use the repo via the http(s) server. In that case example I used Basketbuild to connect to the FTP and list files, but you could adapt the script to use Github API to fetch the release info and build the very same API object, starting from the Github API payload.

> As of this approach which uses only PHP I'm much more familiar with:
> I just had to do a little bit of reasearch on Composer and Flight, but I think I get the hang of it now.
> So I'm pretty sure that integrating an API call to github for fetching the releases of a repository and using these informations for serving the response would be possible. Only thing left to know is if the LineageOS Updater would accept a file from a different location (domain) than the updater script itself.

Yes it will work just fine, there's no check between who servers the API response and where the file is hosted.
