### ISSUE TITLE
Clarification on ROM Integration

### ISSUE THREAD

**Issue by gabeblack** [julianxhokaxhiu/LineageOTA#70]
Hi,

I've read the README on ROM integration. From what I understand, in order to integrate, after the ROM is built (e.g., lineage-17.1-20210207-...zip), I need to extract  the zip file, mount the system.new.dat file, modify the build.prop file within that mounted drive with the lineage.updater.url location pointing to my server, unmount and rebuild the zip file?

Thank you for any clarification. If that is the case, it does seem much more simple to modify packages/apps/Updater/res/values/strings.xml prior with my server location. 

I just wanted to clarify, because I feel I'm missing something big-time (which I probably am since I am super new to building my own ROMs). However, I love the idea of just having my phone point to my own OTA server; and then any modification or new ROM I make I can just push the zip to my OTA server and my phone will pick up the update.

**Comment by julianxhokaxhiu** [comment]
Hi,

no that's not required at all and it's the hard way. The easy way is documented here: https://github.com/julianxhokaxhiu/LineageOTA#lineageos---15x

The build.prop extraction is required to provide a better OTA API response, but it can still be provided only uploading the zip file inside the `builds/full` directory :)

Cheers!

**Comment by gabeblack** [comment]
I think we are misunderstanding one another. Say the OTA server is hosted at https://myotaserver.com. How does my lineage ROM even know to look at https://myotaserver.com? You say by adding that line to build.prop. I've performed a find in the lineageos sources for build.prop, and the only hits are in the build output folder (e.g. out/target/product/<vendor>/system/build.prop). There are no build.prop files in the lineageos source folders. So I think that file is generated as part of the build process. So I don't see how the zip file could contain the build.prop file if I edit the build.prop file after the zip file was created. The lineageos instructions to install the ROM don't say to sideload the zip file and the build.prop file... If I'm somehow supposed to do that, how do I do that? Again, I'm a noob here, so I'm guessing there are ROM installation tidbits that is common knowledge that I'm missing. As I write this, I suspect there is a procedure to edit the build.prop file on the phone directly, which is perhaps what you are instructing to do.

**Comment by julianxhokaxhiu** [comment]
Hi,

No we're understanding each other very well, the only issue here is that what you're asking is part of the common knowledge of ROM build and maintainance. Anyway, to keep it short and sweet for you, all you need is to add this line in `vendor/cm/config/common.mk`:
```sh
PRODUCT_PROPERTY_OVERRIDES += lineage.updater.uri=https://myotaserver.com/api
```
which will add the line in your final `build.prop` that will be packaged in your ROM release zip somewhere.

The path may be different though as I didn't follow the recent LOS releases, so make sure to double check that.

**Comment by gabeblack** [comment]
Nice. Thank you very much! I suspected there was some common knowledge I was missing. I'll try and search around and find how I can get better informed. Thank you so much for the prompt response and help.

**Comment by julianxhokaxhiu** [comment]
No worries, you're welcome :) Enjoy
