### ISSUE TITLE
url issue

### ISSUE THREAD

**Issue by jonnieiti** [julianxhokaxhiu/LineageOTA#77]
added this link to my build prop but fails and so does test file no matter what i do 
sourceforge.net/projects/tweaked-ota/files/updates/signed-ota_update.zip/download

los 18.1

**Comment by julianxhokaxhiu** [comment]
> added this link to my build prop but fails and so does test file no matter what i do sourceforge.net/projects/tweaked-ota/files/updates/signed-ota_update.zip/download
> 
> los 18.1

That's not a OTA issue, but a ROM updater app logic. You need to handle all the redirects and everything Sourceforge does in your own updater code. Closing as invalid.
