### ISSUE TITLE
No updates to Docker image

### ISSUE THREAD

**Issue by bananer** [julianxhokaxhiu/LineageOTA#79]
The Docker image https://hub.docker.com/r/julianxhokaxhiu/lineageota was last updated on Jul 3, so it does not contain new features like #76 

Docker Hub stopped building automatically for free, that's probably the reason. Many projects migrated to bulding Docker images using GitHub actions, e.g. https://github.com/lineageos4microg/docker-lineage-cicd/issues/188

Another option would be to ditch Docker Hub and publish on GitHub Container Registry instead, which simplifies the setup even more. See https://github.com/lineageos4microg/mini_ota/blob/main/.github/workflows/publish.yml for an example.

**Comment by julianxhokaxhiu** [comment]
Thanks for the hint. You're actually right, I'll add an Azure CI manifest to push the container to the hub from there.

I'll see if I can find the time these days to do it sooner rather than later.

**Comment by julianxhokaxhiu** [comment]
CI is now integrated and I just pushed a new build on the latest tag
