### ISSUE TITLE
Not working on php 7.4

### ISSUE THREAD

**Issue by MonkeySaint** [julianxhokaxhiu/LineageOTA#80]
> LineageOTAUnitTest@0.0.1 test
> node tests/lineage.js

<h1>500 Internal Server Error</h1><h3>Undefined offset: 0 (8)</h3><pre>#0 /var/www/LineageOTA/src/Helpers/Build.php(258): flight\Engine->handleError()
#1 /var/www/LineageOTA/src/Helpers/Build.php(70): JX\CmOta\Helpers\Build->removeTrailingDashes()
#2 /var/www/LineageOTA/src/Helpers/Builds.php(153): JX\CmOta\Helpers\Build->__construct()
#3 /var/www/LineageOTA/src/Helpers/Builds.php(49): JX\CmOta\Helpers\Builds->getBuilds()
#4 /var/www/LineageOTA/vendor/mikecao/flight/flight/core/Loader.php(125): JX\CmOta\Helpers\Builds->__construct()
#5 /var/www/LineageOTA/vendor/mikecao/flight/flight/core/Loader.php(81): flight\core\Loader->newInstance()
#6 /var/www/LineageOTA/vendor/mikecao/flight/flight/Engine.php(101): flight\core\Loader->load()
#7 /var/www/LineageOTA/vendor/mikecao/flight/flight/core/Dispatcher.php(198): flight\Engine->__call()
#8 /var/www/LineageOTA/vendor/mikecao/flight/flight/Flight.php(77): flight\core\Dispatcher::invokeMethod()
#9 /var/www/LineageOTA/src/CmOta.php(111): Flight::__callStatic()
#10 /var/www/LineageOTA/vendor/mikecao/flight/flight/core/Dispatcher.php(173): JX\CmOta\CmOta->JX\CmOta\{closure}()
#11 /var/www/LineageOTA/vendor/mikecao/flight/flight/core/Dispatcher.php(145): flight\core\Dispatcher::callFunction()
#12 /var/www/LineageOTA/vendor/mikecao/flight/flight/Engine.php(342): flight\core\Dispatcher::execute()
#13 /var/www/LineageOTA/vendor/mikecao/flight/flight/core/Dispatcher.php(198): flight\Engine->_start()
#14 /var/www/LineageOTA/vendor/mikecao/flight/flight/core/Dispatcher.php(144): flight\core\Dispatcher::invokeMethod()
#15 /var/www/LineageOTA/vendor/mikecao/flight/flight/core/Dispatcher.php(49): flight\core\Dispatcher::execute()
#16 /var/www/LineageOTA/vendor/mikecao/flight/flight/Engine.php(92): flight\core\Dispatcher->run()
#17 /var/www/LineageOTA/vendor/mikecao/flight/flight/core/Dispatcher.php(198): flight\Engine->__call()
#18 /var/www/LineageOTA/vendor/mikecao/flight/flight/Flight.php(77): flight\core\Dispatcher::invokeMethod()
#19 /var/www/LineageOTA/src/CmOta.php(69): Flight::__callStatic()
#20 /var/www/LineageOTA/index.php(60): JX\CmOta\CmOta->run()

**Comment by julianxhokaxhiu** [comment]
Can you put
```php
var_dump($token);
```
Before [this line](https://github.com/julianxhokaxhiu/LineageOTA/blob/2.0/src/Helpers/Build.php#L262), try again and post the result?

Otherwise post an how-to reproduce and I'll be happy to check.

**Comment by MonkeySaint** [comment]
I am getting the same output. Thanks for the quick responce
```╰─$ npm run test

> LineageOTAUnitTest@0.0.1 test
> node tests/lineage.js

<h1>500 Internal Server Error</h1><h3>Undefined offset: 0 (8)</h3><pre>#0 /var/www/LineageOTA/src/Helpers/Build.php(259): flight\Engine->handleError()
#1 /var/www/LineageOTA/src/Helpers/Build.php(70): JX\CmOta\Helpers\Build->removeTrailingDashes()
#2 /var/www/LineageOTA/src/Helpers/Builds.php(153): JX\CmOta\Helpers\Build->__construct()
#3 /var/www/LineageOTA/src/Helpers/Builds.php(49): JX\CmOta\Helpers\Builds->getBuilds()
#4 /var/www/LineageOTA/vendor/mikecao/flight/flight/core/Loader.php(125): JX\CmOta\Helpers\Builds->__construct()
#5 /var/www/LineageOTA/vendor/mikecao/flight/flight/core/Loader.php(81): flight\core\Loader->newInstance()
#6 /var/www/LineageOTA/vendor/mikecao/flight/flight/Engine.php(101): flight\core\Loader->load()
#7 /var/www/LineageOTA/vendor/mikecao/flight/flight/core/Dispatcher.php(198): flight\Engine->__call()
#8 /var/www/LineageOTA/vendor/mikecao/flight/flight/Flight.php(77): flight\core\Dispatcher::invokeMethod()
#9 /var/www/LineageOTA/src/CmOta.php(111): Flight::__callStatic()
#10 /var/www/LineageOTA/vendor/mikecao/flight/flight/core/Dispatcher.php(173): JX\CmOta\CmOta->JX\CmOta\{closure}()
#11 /var/www/LineageOTA/vendor/mikecao/flight/flight/core/Dispatcher.php(145): flight\core\Dispatcher::callFunction()
#12 /var/www/LineageOTA/vendor/mikecao/flight/flight/Engine.php(342): flight\core\Dispatcher::execute()
#13 /var/www/LineageOTA/vendor/mikecao/flight/flight/core/Dispatcher.php(198): flight\Engine->_start()
#14 /var/www/LineageOTA/vendor/mikecao/flight/flight/core/Dispatcher.php(144): flight\core\Dispatcher::invokeMethod()
#15 /var/www/LineageOTA/vendor/mikecao/flight/flight/core/Dispatcher.php(49): flight\core\Dispatcher::execute()
#16 /var/www/LineageOTA/vendor/mikecao/flight/flight/Engine.php(92): flight\core\Dispatcher->run()
#17 /var/www/LineageOTA/vendor/mikecao/flight/flight/core/Dispatcher.php(198): flight\Engine->__call()
#18 /var/www/LineageOTA/vendor/mikecao/flight/flight/Flight.php(77): flight\core\Dispatcher::invokeMethod()
#19 /var/www/LineageOTA/src/CmOta.php(69): Flight::__callStatic()
#20 /var/www/LineageOTA/index.php(60): JX\CmOta\CmOta->run()
#21 {main}</pre>
```

I installed via compser from whats on the github. Installed compser from there php file and installed it to my bin. On ubuntu server 20.04. I am using nginx and setup the rewrite rule.

Here is my nginx config

```
server {
        listen 80;
        listen [::]:80;
        root /var/www/LineageOTA;
        index index.html index.htm index.nginx-debian.html index.php;
        server_name ota.pixeldust-project.com;

       location / {
                try_files $uri $uri/ /index.php;
        }

                location ~ \.php$ {
                include snippets/fastcgi-php.conf;
                fastcgi_pass unix:/var/run/php/php7.4-fpm.sock;
        }
        
                location /builds {
                autoindex on;
                autoindex_exact_size off;
                try_files $uri $uri/ /index.php?$args;
        }
}
```

**Comment by julianxhokaxhiu** [comment]
Ok thanks, I'll check that later and let you know.

**Comment by MonkeySaint** [comment]
Thanks

**Comment by julianxhokaxhiu** [comment]
I was trying to replicate your issue here locally, but I ended having one missing piece of the puzzle: can you let me know which API endpoint you expect to call on top of the OTA?

Eg.
```
/api/v1/hammerhead/nightly
```

//EDIT: The more I look at your ZIP file the more I think it's not compatible with this OTA system. Is your project LOS based? The name looks far away from lineage standard: `PixelDust-SaltedCaramel-caf-blueline-user-20220118-0027.zip`

//EDIT2: If I add one of the official lineageos ZIP files into the OTA, with PHP 7.4 I get a valid answer and it works as expected:
```json
{
  "id": null,
  "response": [
    {
      "incremental": "",
      "api_level": "",
      "url": "http://localhost//builds/full/lineage-18.1-20220114-nightly-vayu-signed.zip",
      "timestamp": 1642716660,
      "md5sum": "123e878c1787f00bb0b604261f664c0f",
      "changes": "",
      "channel": "nightly",
      "filename": "lineage-18.1-20220114-nightly-vayu-signed.zip",
      "romtype": "nightly",
      "datetime": 1642716660,
      "version": "18.1",
      "id": "bd00f6605ab4270b2ad1822471247669d462e69455a91d5fc7b105b0de1ed529",
      "size": 1103188659
    }
  ],
  "error": null
}
```
So I guess your ZIP file ( or project ) is not compatibile with this OTA system which expects the ZIP to be named using the LOS/CM format.

**Comment by MonkeySaint** [comment]
Yeah it's not based on lineageos but we do have our version in their updater. But you have given me enough to go on. Thank you.

**Comment by julianxhokaxhiu** [comment]
Cheers!
