### ISSUE TITLE
adapt new snapshot filename schema

### ISSUE THREAD

**Issue by emfox** [julianxhokaxhiu/LineageOTA#9]
the new cm snapshot filename is like this cm-13.0-20160419-SNAPSHOT-ZNH0EAO2O0-bacon.zip, with an extra version of ZNH0EAO2O0, this makes our ota server 500 error:

<h1>500 Internal Server Error</h1><h3>Undefined offset: 0 (8)</h3><pre>#0 /app/src/Helpers/Build.php(215): flight\Engine->handleError(8, 'Undefined offse...', '/app/src/Helper...', 215, Array)
#1 /app/src/Helpers/Build.php(62): JX\CmOta\Helpers\Build->removeTrailingDashes(Array)
#2 /app/src/Helpers/Builds.php(130): JX\CmOta\Helpers\Build->__construct('cm-13.1-2016041...', '/app/builds/ful...')
#3 /app/src/Helpers/Builds.php(49): JX\CmOta\Helpers\Builds->getBuilds()
#4 /app/vendor/mikecao/flight/flight/core/Loader.php(123): JX\CmOta\Helpers\Builds->__construct()
#5 /app/vendor/mikecao/flight/flight/core/Loader.php(80): flight\core\Loader->newInstance('\JX\CmOta\Helpe...', Array)
#6 /app/vendor/mikecao/flight/flight/Engine.php(69): flight\core\Loader->load('builds', true)
#7 /app/vendor/mikecao/flight/flight/core/Dispatcher.php(191): flight\Engine->__call('builds', Array)
#8 /app/vendor/mikecao/flight/flight/core/Dispatcher.php(191): flight\Engine->builds()
#9 /app/vendor/mikecao/flight/flight/Flight.php(76): flight\core\Dispatcher::invokeMethod(Array, Array)
#10 /app/src/CmOta.php(108): Flight::__callStatic('builds', Array)
#11 /app/src/CmOta.php(108): Flight::builds()
#12 /app/vendor/mikecao/flight/flight/core/Dispatcher.php(160): JX\CmOta\CmOta->JX\CmOta{closure}()
#13 /app/vendor/mikecao/flight/flight/core/Dispatcher.php(143): flight\core\Dispatcher::callFunction(Object(Closure), Array)
#14 /app/vendor/mikecao/flight/flight/Engine.php(313): flight\core\Dispatcher::execute(Object(Closure), Array)
#15 /app/vendor/mikecao/flight/flight/core/Dispatcher.php(191): flight\Engine->_start()
#16 /app/vendor/mikecao/flight/flight/core/Dispatcher.php(142): flight\core\Dispatcher::invokeMethod(Array, Array)
#17 /app/vendor/mikecao/flight/flight/core/Dispatcher.php(48): flight\core\Dispatcher::execute(Array, Array)
#18 /app/vendor/mikecao/flight/flight/Engine.php(64): flight\core\Dispatcher->run('start', Array)
#19 /app/vendor/mikecao/flight/flight/core/Dispatcher.php(191): flight\Engine->__call('start', Array)
#20 /app/vendor/mikecao/flight/flight/core/Dispatcher.php(191): flight\Engine->start()
#21 /app/vendor/mikecao/flight/flight/Flight.php(76): flight\core\Dispatcher::invokeMethod(Array, Array)
#22 /app/src/CmOta.php(80): Flight::__callStatic('start', Array)
#23 /app/src/CmOta.php(80): Flight::start()
#24 /app/index.php(35): JX\CmOta\CmOta->run()
#25 {main}</pre>

**Comment by julianxhokaxhiu** [comment]
Can you please try it now?

**Comment by emfox** [comment]
Tried and it's OK now.

**Comment by julianxhokaxhiu** [comment]
thank you :)
